name: Docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install json-schema-for-humans
        run: |
          python -m pip install --upgrade pip
          pip install json-schema-for-humans
      - name: Build with json-schema-for-humans
        run: |
          mkdir -p docs/_build/html
          generate-schema-doc "schema/plugin-metadata.json" docs/_build/html/index.html
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
